
language: node_js
node_js:
   - "stable"
script:
  - npm run test && npm run coverage

# deploy:
#   provider: heroku
#   api_key:
#   secure: eZEc67+fHCt878Fh7ixS/wkUir7ycaIh1FQhDkaJKtHPipVFYLMEJckttosEAFU9WZeI/SOD9R7d2lUpe5bZPNsYMGY5tbcg2Sjq4DZzi24sxqUfmw/kvgtY717e78IetsYoEjz+K/FnH4vPe4qMIplKjeneofsd0rjrzIl4iSA9P0MGK5LSza1NrntVVcnYMEdKvpIlKvhaI1eZ45IBrm1jP3xAXXpDfjJecXDFa3nP1FTT/8kdxMFj1w0xXXca2AnTJZnanxYYwaRllETv54zlaKfHXpqFo1CQPk0xUq6D5E38uDZRM2vEYqAsZo9IeRMGj2bIttMGwWDaUGgqZT+nzHC4AwLpbETbG71PaJxiRwab+3m+8VsnT/Lds6gtleQHpFrfYRZFh1t1D615vykWB5iX3xpB5D9nsJheiMQs8jxdlKDkZxZB5cvfrf56fBEzBvGorXhLV8p6QtxDDvWOaaSKuERDfNPxce5ENbe6UMey7ur22e7GV48AsdLIcFejVabKrbl94apJBFHKGT14ekF5sS1aXSyncOuAYdNsOqiMXMainlagwiJD7Flnb2aXngMf0Dh/mUR3heOCqptOwY15z+U5IdstZT63xsFwPhRkxujnvn2ar9pmAaGX2ZnJW6Vo+JgywbZ7JLoxtReFNhO2b5hE46kFQiSJkz4=
#   app: stackoverflow-lite
