trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    yarn install
  displayName: 'install dependencies'

- script: echo $(NODE_PATH)
  displayName: "checking node path"

- script: |
    yarn build
  displayName: "build project"

- task: DockerCompose@0
  displayName: 'docker-compose down'
  condition: always()
  inputs:
    action: 'Run a Docker Compose command'
    dockerComposeCommand: 'down --remove-orphans'

- task: DockerCompose@0
  displayName: 'docker-compose up'
  inputs:
    action: 'Run a Docker Compose command'
    dockerComposeCommand: 'up -d --build'

- script: yarn run migration:run:staging
  displayName: 'run database migration'

- script: yarn run test
  displayName: 'run tests'

- task: DockerCompose@0
  displayName: 'docker-compose down'
  condition: always()
  inputs:
    action: 'Run a Docker Compose command'
    dockerComposeCommand: 'down'
    
